/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";

export interface DAOCake_Rep_ProposalsInterface extends utils.Interface {
  functions: {
    "exists(bytes32)": FunctionFragment;
    "getProposal(bytes32)": FunctionFragment;
    "getProposalAtIndex(uint256)": FunctionFragment;
    "getProposalCount()": FunctionFragment;
    "getProposalVotes(bytes32)": FunctionFragment;
    "getVotesCount(bytes32)": FunctionFragment;
    "newProposal(bytes32,bytes32,string,string,string,string,uint256,uint16,uint8)": FunctionFragment;
    "remProposal(bytes32)": FunctionFragment;
    "voteAdd(bytes32,bytes32,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "exists"
      | "getProposal"
      | "getProposalAtIndex"
      | "getProposalCount"
      | "getProposalVotes"
      | "getVotesCount"
      | "newProposal"
      | "remProposal"
      | "voteAdd"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "exists",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalAtIndex",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalVotes",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotesCount",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "newProposal",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "remProposal",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "voteAdd",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "exists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "newProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteAdd", data: BytesLike): Result;

  events: {
    "LogNewProposal(address,bytes32,string,string,string,string,uint256,uint16,uint16,uint16,uint8)": EventFragment;
    "LogRemProposal(address,bytes32)": EventFragment;
    "LogUpdateProposal(address,bytes32,string,string,string,string,uint256,uint16,uint16,uint16,uint8,uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogNewProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogRemProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogUpdateProposal"): EventFragment;
}

export interface LogNewProposalEventObject {
  sender: string;
  key: string;
  name: string;
  uuid: string;
  doc_cid: string;
  ref_id: string;
  total: BigNumber;
  nVotes: number;
  nVotesFor: number;
  nVotesRequired: number;
  proposalType: number;
}
export type LogNewProposalEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    number,
    number,
    number,
    number
  ],
  LogNewProposalEventObject
>;

export type LogNewProposalEventFilter = TypedEventFilter<LogNewProposalEvent>;

export interface LogRemProposalEventObject {
  sender: string;
  key: string;
}
export type LogRemProposalEvent = TypedEvent<
  [string, string],
  LogRemProposalEventObject
>;

export type LogRemProposalEventFilter = TypedEventFilter<LogRemProposalEvent>;

export interface LogUpdateProposalEventObject {
  sender: string;
  key: string;
  name: string;
  uuid: string;
  doc_cid: string;
  ref_id: string;
  total: BigNumber;
  nVotes: number;
  nVotesFor: number;
  nVotesRequired: number;
  proposalType: number;
  decisionStatus: number;
}
export type LogUpdateProposalEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    number,
    number,
    number,
    number,
    number
  ],
  LogUpdateProposalEventObject
>;

export type LogUpdateProposalEventFilter =
  TypedEventFilter<LogUpdateProposalEvent>;

export interface DAOCake_Rep_Proposals extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DAOCake_Rep_ProposalsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    exists(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getProposal(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        number,
        number
      ] & {
        orgKey: string;
        memberKey: string;
        name: string;
        uuid: string;
        doc_cid: string;
        ref_id: string;
        total: BigNumber;
        nVotes: number;
        proposalType: number;
      }
    >;

    getProposalAtIndex(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { key: string }>;

    getProposalCount(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { count: BigNumber }>;

    getProposalVotes(
      proposalKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string[]] & { array: string[] }>;

    getVotesCount(
      proposalKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number] & {
        votes: number;
        votesFor: number;
        votesRequired: number;
      }
    >;

    newProposal(
      key: PromiseOrValue<BytesLike>,
      memberKey: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<string>,
      uuid: PromiseOrValue<string>,
      doc_cid: PromiseOrValue<string>,
      ref_id: PromiseOrValue<string>,
      total: PromiseOrValue<BigNumberish>,
      votesRequired: PromiseOrValue<BigNumberish>,
      proposalType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    remProposal(
      key: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    voteAdd(
      proposalKey: PromiseOrValue<BytesLike>,
      memberKey: PromiseOrValue<BytesLike>,
      voteFor: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  exists(
    key: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getProposal(
    key: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      BigNumber,
      number,
      number
    ] & {
      orgKey: string;
      memberKey: string;
      name: string;
      uuid: string;
      doc_cid: string;
      ref_id: string;
      total: BigNumber;
      nVotes: number;
      proposalType: number;
    }
  >;

  getProposalAtIndex(
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getProposalCount(overrides?: CallOverrides): Promise<BigNumber>;

  getProposalVotes(
    proposalKey: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getVotesCount(
    proposalKey: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [number, number, number] & {
      votes: number;
      votesFor: number;
      votesRequired: number;
    }
  >;

  newProposal(
    key: PromiseOrValue<BytesLike>,
    memberKey: PromiseOrValue<BytesLike>,
    name: PromiseOrValue<string>,
    uuid: PromiseOrValue<string>,
    doc_cid: PromiseOrValue<string>,
    ref_id: PromiseOrValue<string>,
    total: PromiseOrValue<BigNumberish>,
    votesRequired: PromiseOrValue<BigNumberish>,
    proposalType: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  remProposal(
    key: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  voteAdd(
    proposalKey: PromiseOrValue<BytesLike>,
    memberKey: PromiseOrValue<BytesLike>,
    voteFor: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    exists(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getProposal(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        number,
        number
      ] & {
        orgKey: string;
        memberKey: string;
        name: string;
        uuid: string;
        doc_cid: string;
        ref_id: string;
        total: BigNumber;
        nVotes: number;
        proposalType: number;
      }
    >;

    getProposalAtIndex(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getProposalCount(overrides?: CallOverrides): Promise<BigNumber>;

    getProposalVotes(
      proposalKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getVotesCount(
      proposalKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [number, number, number] & {
        votes: number;
        votesFor: number;
        votesRequired: number;
      }
    >;

    newProposal(
      key: PromiseOrValue<BytesLike>,
      memberKey: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<string>,
      uuid: PromiseOrValue<string>,
      doc_cid: PromiseOrValue<string>,
      ref_id: PromiseOrValue<string>,
      total: PromiseOrValue<BigNumberish>,
      votesRequired: PromiseOrValue<BigNumberish>,
      proposalType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    remProposal(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    voteAdd(
      proposalKey: PromiseOrValue<BytesLike>,
      memberKey: PromiseOrValue<BytesLike>,
      voteFor: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[number, BigNumber] & { action: number; value: BigNumber }>;
  };

  filters: {
    "LogNewProposal(address,bytes32,string,string,string,string,uint256,uint16,uint16,uint16,uint8)"(
      sender?: null,
      key?: null,
      name?: null,
      uuid?: null,
      doc_cid?: null,
      ref_id?: null,
      total?: null,
      nVotes?: null,
      nVotesFor?: null,
      nVotesRequired?: null,
      proposalType?: null
    ): LogNewProposalEventFilter;
    LogNewProposal(
      sender?: null,
      key?: null,
      name?: null,
      uuid?: null,
      doc_cid?: null,
      ref_id?: null,
      total?: null,
      nVotes?: null,
      nVotesFor?: null,
      nVotesRequired?: null,
      proposalType?: null
    ): LogNewProposalEventFilter;

    "LogRemProposal(address,bytes32)"(
      sender?: null,
      key?: null
    ): LogRemProposalEventFilter;
    LogRemProposal(sender?: null, key?: null): LogRemProposalEventFilter;

    "LogUpdateProposal(address,bytes32,string,string,string,string,uint256,uint16,uint16,uint16,uint8,uint8)"(
      sender?: null,
      key?: null,
      name?: null,
      uuid?: null,
      doc_cid?: null,
      ref_id?: null,
      total?: null,
      nVotes?: null,
      nVotesFor?: null,
      nVotesRequired?: null,
      proposalType?: null,
      decisionStatus?: null
    ): LogUpdateProposalEventFilter;
    LogUpdateProposal(
      sender?: null,
      key?: null,
      name?: null,
      uuid?: null,
      doc_cid?: null,
      ref_id?: null,
      total?: null,
      nVotes?: null,
      nVotesFor?: null,
      nVotesRequired?: null,
      proposalType?: null,
      decisionStatus?: null
    ): LogUpdateProposalEventFilter;
  };

  estimateGas: {
    exists(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposal(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposalAtIndex(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposalCount(overrides?: CallOverrides): Promise<BigNumber>;

    getProposalVotes(
      proposalKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVotesCount(
      proposalKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    newProposal(
      key: PromiseOrValue<BytesLike>,
      memberKey: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<string>,
      uuid: PromiseOrValue<string>,
      doc_cid: PromiseOrValue<string>,
      ref_id: PromiseOrValue<string>,
      total: PromiseOrValue<BigNumberish>,
      votesRequired: PromiseOrValue<BigNumberish>,
      proposalType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    remProposal(
      key: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    voteAdd(
      proposalKey: PromiseOrValue<BytesLike>,
      memberKey: PromiseOrValue<BytesLike>,
      voteFor: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    exists(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposal(
      key: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposalAtIndex(
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposalCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getProposalVotes(
      proposalKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVotesCount(
      proposalKey: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    newProposal(
      key: PromiseOrValue<BytesLike>,
      memberKey: PromiseOrValue<BytesLike>,
      name: PromiseOrValue<string>,
      uuid: PromiseOrValue<string>,
      doc_cid: PromiseOrValue<string>,
      ref_id: PromiseOrValue<string>,
      total: PromiseOrValue<BigNumberish>,
      votesRequired: PromiseOrValue<BigNumberish>,
      proposalType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    remProposal(
      key: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    voteAdd(
      proposalKey: PromiseOrValue<BytesLike>,
      memberKey: PromiseOrValue<BytesLike>,
      voteFor: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
